import type { Conversation } from "@/lib/conversations/types";

export type {
  Channel,
  Conversation,
  ConversationStatus,
  Message,
  MessageRole,
} from "@/lib/conversations/types";

export const conversations: Conversation[] = [
  {
    id: "conv-1048",
    customer: {
      id: "customer-1048",
      name: "林晓雨",
      initials: "林",
      phone: "138 **** 2174",
      email: "xiaoyu.lin@example.com",
      city: "上海",
      plan: "Pro 年付",
      since: "2024-11-08",
    },
    channel: "wechat",
    status: "open",
    priority: "high",
    unread: 2,
    lastMessage: "物流三天没更新了，能帮我看一下吗？",
    updatedAt: "2 分钟前",
    assignee: "未分配",
    tags: ["基础数据", "物流", "高价值客户"],
    aiManaged: false,
    order: {
      id: "SO-20260703-1842",
      amount: "¥ 1,299.00",
      status: "运输中",
      placedAt: "2026-06-28 14:32",
    },
    messages: [
      {
        id: "m-1",
        role: "customer",
        content: "你好，我上周买的空气净化器还没有收到。",
        time: "14:21",
      },
      {
        id: "m-2",
        role: "assistant",
        sender: "Luma AI",
        content:
          "你好，晓雨。我查到订单 SO-20260703-1842 已于 6 月 29 日发出，目前状态是运输中。",
        time: "14:21",
      },
      {
        id: "m-3",
        role: "customer",
        content: "物流三天没更新了，能帮我看一下吗？",
        time: "14:23",
      },
      {
        id: "m-4",
        role: "system",
        content: "AI 检测到物流异常，已转交人工客服",
        time: "14:23",
      },
    ],
  },
  {
    id: "conv-1047",
    customer: {
      id: "customer-1047",
      name: "陈屿",
      initials: "陈",
      phone: "186 **** 9021",
      email: "chenyu@example.com",
      city: "杭州",
      plan: "基础版",
      since: "2025-08-16",
    },
    channel: "web",
    status: "open",
    priority: "normal",
    unread: 1,
    lastMessage: "怎么修改发票抬头？",
    updatedAt: "8 分钟前",
    assignee: "未分配",
    tags: ["基础数据", "发票"],
    aiManaged: false,
    messages: [
      {
        id: "m-5",
        role: "customer",
        content: "怎么修改发票抬头？",
        time: "14:17",
      },
    ],
  },
  {
    id: "conv-1046",
    customer: {
      id: "customer-1046",
      name: "许知远",
      initials: "许",
      phone: "177 **** 1105",
      email: "zhiyuan.xu@example.com",
      city: "北京",
      plan: "企业版",
      since: "2023-12-02",
    },
    channel: "email",
    status: "pending",
    priority: "normal",
    unread: 0,
    lastMessage: "请把续费报价单发到我的邮箱，谢谢。",
    updatedAt: "26 分钟前",
    assignee: "未分配",
    tags: ["基础数据", "续费", "企业客户"],
    aiManaged: false,
    messages: [
      {
        id: "m-6",
        role: "customer",
        content: "请把续费报价单发到我的邮箱，谢谢。",
        time: "13:59",
      },
      {
        id: "m-7",
        role: "agent",
        sender: "初始化数据",
        content: "收到，我确认席位数量后会在今天下班前发给你。",
        time: "14:02",
      },
    ],
  },
  {
    id: "conv-1045",
    customer: {
      id: "customer-1045",
      name: "吴晨",
      initials: "吴",
      phone: "151 **** 6320",
      email: "wuchen@example.com",
      city: "成都",
      plan: "Pro 月付",
      since: "2026-02-18",
    },
    channel: "web",
    status: "open",
    priority: "normal",
    unread: 0,
    lastMessage: "已经解决了，感谢！",
    updatedAt: "1 小时前",
    assignee: "未分配",
    tags: ["基础数据", "产品使用"],
    aiManaged: false,
    messages: [
      {
        id: "m-8",
        role: "customer",
        content: "已经解决了，感谢！",
        time: "13:24",
      },
    ],
  },
  {
    id: "conv-1044",
    customer: {
      id: "customer-1044",
      name: "孙可",
      initials: "孙",
      phone: "133 **** 4489",
      email: "sunke@example.com",
      city: "深圳",
      plan: "基础版",
      since: "2026-05-09",
    },
    channel: "wechat",
    status: "pending",
    priority: "normal",
    unread: 0,
    lastMessage: "周末有人处理退款吗？",
    updatedAt: "2 小时前",
    assignee: "未分配",
    tags: ["基础数据", "退款"],
    aiManaged: false,
    messages: [
      {
        id: "m-9",
        role: "customer",
        content: "周末有人处理退款吗？",
        time: "12:16",
      },
    ],
  },
];
